#This file stores configuration options for Iris, such as the currently active shaderpack
#Wed May 27 12:54:12 BST 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=6
shaderPack=photon_v1.3b.zip
enableShaders=true
